### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by masonreznov** [kushalvyas/Bag-of-Visual-Words-Python#15]
```python
Traceback (most recent call last):
  File "Bag.py", line 160, in <module>
    bov.trainModel()
  File "Bag.py", line 50, in trainModel
    bov_descriptor_stack = self.bov_helper.formatND(self.descriptor_list)
  File "C:\Users\birdman\OneDrive\Project\MY STUFFS\bag of visual word\Bag-of-Visual-Words-Python-master\Bag-of-Visual-Words-Python-master\helpers.py", line 85, in formatND
    vStack = np.array(l[0])
IndexError: list index out of range
```

**Comment by masonreznov** [comment]
Covert "vocab" into 2d array. Instead of "self.bov_helper.scale.transform(vocab)" try "self.bov_helper.scale.transform(np.atleast_2d(vocab)) ". Also "import numpy as np" before this step.

_this helped_

**Comment by nys09** [comment]
I have the same error. But I am unable to solve it by following your suggestion. I replaced line 89 in Bag.py to vocab = self.bov_helper.scale.transform(np.atleast_2d(vocab)) as directed by you. I am still getting the same error.

**Comment by prathmanu** [comment]
Same issue here ..

**Comment by prathmanu** [comment]
> I have the same error. But I am unable to solve it by following your suggestion. I replaced line 89 in Bag.py to vocab = self.bov_helper.scale.transform(np.atleast_2d(vocab)) as directed by you. I am still getting the same error. Can you please help me with this ?

change Line 140 from word = each.split("/")[-1] to word = each.split("\\")[-1]

**Comment by nguyenquyet27** [comment]
After I change Line 140 from word = each.split("/")[-1] to ' \ ' and convert self.bov_helper.scale.transform(np.atleast_2d(vocab)) I 
still not out of error

**Comment by prathmanu** [comment]
try self.bov_helper.scale.transform(vocab) (don’t use  np.atleast_2d) , change Line 140 from word = each.split("/")[-1] to ' \ ' (Slash )

**Comment by prathmanu** [comment]
> After I change Line 140 from word = each.split("/")[-1] to ' \ ' and convert self.bov_helper.scale.transform(np.atleast_2d(vocab)) I
> still not out of error

try self.bov_helper.scale.transform(vocab) (don’t use np.atleast_2d) , change Line 140 from word = each.split("/")[-1] to ' \ ' If still the same  error ,debug getFiles method(Line 129) in helper.py

**Comment by nepoleonk** [comment]
I have tried all the methods given above. I am still having the problem. Thank you in advance
