### ISSUE TITLE
licence for master thesis

### ISSUE THREAD

**Issue by pabloheimplatz** [kushalvyas/Bag-of-Visual-Words-Python#4]
Hi Kushal,
I have a simliar problem (but with a completely different dataset) in my master thesis. (I'm also studying computer science here in Germany) And it would be perfect if I can quote and use some of your code ideas in my own master thesis. So I would ask, if it is possible that you add an licence (just for usage in science) in your repository?

Thank you in advance.
Best Regards,
Pablo

**Comment by kushalvyas** [comment]
@Pablo , I've added an MIT License . Please feel free to use this repository in accordance with this license.

**Comment by pabloheimplatz** [comment]
Thank you very much!
